// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function Open(arg1:string):Promise<void>;

export function Scrape():Promise<{[key: string]: {[key: string]: number}}>;
